### ISSUE TITLE
pare tipow

### ISSUE THREAD

**Issue by i008** [getbettersoon/gbs_energy_etl#1]
-  Add a requirements file or other way to recreate/setup the environment

https://github.com/getbettersoon/gbs_energy_etl/blob/main/gbs_energy_etl/create_tables.py#L10
This is bad design, the abstractions should look more like delete_tables(conn, [list_of_table_names]) using something imported inside a function is usually not a good idea. its hard to reuse the functions etc.

Same applies for the create_tables.

**Comment by getbettersoon** [comment]
fixed
